wip av/krakenclient
northwesternfintech/desk-monorepo pull request #34
Opened 2024-10-18 22:40 UTC by aidanvillasenor

### Description

### Testing

### Impact

### Other

2024-10-18 23:04 UTC, echavemann commented
Draft, fix your git config

2024-10-19 01:44 UTC, echavemann commented on src/pysrc/adapters/kraken/containers.py
> +@dataclass
still dont like dataclass

2024-10-19 01:44 UTC, echavemann commented on src/pysrc/adapters/kraken/containers.py
> +    asset2: Asset
yea the other asset here is USDT, which we dont support as an Asset which you would see if you checked

2024-10-19 01:45 UTC, echavemann commented
this pr is like this for a reason
https://github.com/northwesternfintech/desk-monorepo/pull/30

2024-10-19 01:45 UTC, echavemann commented
> this pr is like this for a reason #30

directory structure is currently incorrect

2024-10-19 01:46 UTC, echavemann commented on src/pysrc/adapters/kraken/kraken_client.py
> +    def __init__(self, base_url: str = "https://api.kraken.com/0/public/", currency: str = "USDT"):
currency is a trash arg, why would I care

2024-10-19 01:46 UTC, echavemann commented on src/pysrc/adapters/messages.py
> +        self.feedcode = feedcode
lmao

2024-10-19 01:47 UTC, echavemann commented on src/pysrc/adapters/messages.py
> +class SpreadMessage:
this doesnt go into the generic messages, put it in containers

2024-10-19 03:08 UTC, rewong03 commented
iirc the docs have example responses, def should consider using them in unit tests

2024-10-19 03:22 UTC, rewong03 commented on src/pysrc/adapters/kraken/containers.py
> +@dataclass
don't like dataclass == like boilerplate

2024-10-19 03:23 UTC, rewong03 commented on src/pysrc/adapters/kraken/future/containers.py
needs a merge with main?

2024-10-19 03:24 UTC, rewong03 commented on src/pysrc/adapters/kraken/kraken_client.py
> +        self._kraken_to_asset = {"XXBTZUSD" : "BTC"} # UNFINISHED
what is this for?

2024-10-19 03:25 UTC, rewong03 commented on src/pysrc/adapters/kraken/kraken_client.py
> +    def __init__(self, base_url: str = "https://api.kraken.com/0/public/", currency: str = "USDT"):
To keep consistency, check #30 for how to handle base url for test vs live

2024-10-19 03:27 UTC, rewong03 commented on src/pysrc/adapters/kraken/kraken_client.py
> +        except requests.exceptions.RequestException as e:
why catch this in the first place? the rest of your functions assume a success so this will definitely cause downstream issues when marshalling the response

2024-10-19 03:29 UTC, rewong03 commented on src/pysrc/adapters/kraken/kraken_client.py
> +        response = self._get("Assets", params)
nit, i think the following is more explicit:
```
route = "Assets"
params = ...
response = self._get(route, params)
```

2024-10-19 03:31 UTC, rewong03 commented on src/pysrc/adapters/kraken/kraken_client.py
> +            status = AssetStatus[asset_data['status'].replace(' ', '_').upper()]
I think there should be helper functions for doing `str_to_enum` and `enum_to_str` conversions (maybe in a `utils.py` file)

2024-10-19 03:32 UTC, rewong03 commented on src/pysrc/adapters/kraken/kraken_client.py
> +    def get_tradeable_asset_pairs(self, pairs: list[AssetPair], info: str = "info") -> Dict[str, AssetPairInfo]:
imo i feel like info should be an enum

2024-10-19 03:35 UTC, rewong03 commented on src/pysrc/adapters/kraken/kraken_client.py
> +        assert info in ["info", "leverage", "fees", "margin"]
@echavemann thoughts on doing input validation for wrappers? imo its more sane/manageable to have kraken return an error for invalid inputs

2024-10-19 03:42 UTC, rewong03 commented on src/pysrc/adapters/kraken/kraken_client.py
> +        if since:
just searched this up, but for the requests library if a value in params is none then the key won't be included in the request query so no need to check

2024-10-19 17:51 UTC, aidanvillasenor commented on src/pysrc/adapters/kraken/kraken_client.py
> +    def get_tradeable_asset_pairs(self, pairs: list[AssetPair], info: str = "info") -> Dict[str, AssetPairInfo]:
chk

2024-10-19 17:52 UTC, aidanvillasenor commented on src/pysrc/adapters/kraken/kraken_client.py
> +            status = AssetStatus[asset_data['status'].replace(' ', '_').upper()]
@echavemann thoughts

2024-10-19 17:53 UTC, aidanvillasenor commented on src/pysrc/adapters/kraken/kraken_client.py
> +        except requests.exceptions.RequestException as e:
100% good catch

2024-10-19 17:55 UTC, aidanvillasenor commented on src/pysrc/adapters/kraken/kraken_client.py
> +        self._kraken_to_asset = {"XXBTZUSD" : "BTC"} # UNFINISHED
kraken uses diff names than we do for our enums. They call btc, at least btc in the form that we care about, "XXBTZUSD" so we need to be able to map our assets to and from their strings to the names of our enums

2024-10-19 17:56 UTC, aidanvillasenor commented on src/pysrc/adapters/kraken/kraken_client.py
> +            status = AssetStatus[asset_data['status'].replace(' ', '_').upper()]
we could have helpers, but tbf it seems like python alr has decent enough built in functionality for these conversions

2024-10-19 18:02 UTC, aidanvillasenor commented on src/pysrc/adapters/kraken/kraken_client.py
> +        if since:
ye sg

2024-10-19 18:03 UTC, aidanvillasenor commented on src/pysrc/adapters/kraken/kraken_client.py
> +        assert info in ["info", "leverage", "fees", "margin"]
either works. For this particular case its prob gonna turn into an enum, so should be fine

2024-10-19 20:44 UTC, echavemann commented on src/pysrc/adapters/kraken/containers.py
> +@dataclass
boilerplate > magic

2024-10-19 20:44 UTC, echavemann commented on src/pysrc/adapters/kraken/containers.py
> +@dataclass
if i liked magic id have no types and probably no classes :)

2024-10-19 20:47 UTC, echavemann commented on src/pysrc/adapters/kraken/kraken_client.py
> +            status = AssetStatus[asset_data['status'].replace(' ', '_').upper()]
nah ryan is right

2024-10-19 20:47 UTC, echavemann commented on src/pysrc/adapters/kraken/kraken_client.py
> +        assert info in ["info", "leverage", "fees", "margin"]
yea that one shud def be an enum, but i agree with ryan. if we send a malformed order we shud crash

2024-10-19 20:51 UTC, rewong03 commented on src/pysrc/adapters/kraken/kraken_client.py
> +        if since:
also u should double check with the docs whether you should be using `params` or `data` when making the request. with the api i'm working with they change between functions

2024-10-19 20:51 UTC, rewong03 commented on src/pysrc/adapters/kraken/kraken_client.py
> +        self._kraken_to_asset = {"XXBTZUSD" : "BTC"} # UNFINISHED
I think u should map to the asset enum instead of raw string

2024-10-19 21:55 UTC, aidanvillasenor commented on src/pysrc/adapters/kraken/kraken_client.py
> +        self._kraken_to_asset = {"XXBTZUSD" : "BTC"} # UNFINISHED
yeah didn't even consider that. will do

2024-10-19 23:43 UTC, echavemann commented on src/pysrc/adapters/kraken/future/containers.py
why del

2024-10-19 23:44 UTC, echavemann commented on src/pysrc/adapters/kraken/spot/kraken_client.py
> +        self._kraken_to_asset = {"XXBTZUSD": Asset.BTC}
why are these like this

2024-10-19 23:44 UTC, echavemann commented on src/pysrc/adapters/kraken/spot/kraken_client.py
> +    def __init__(self, use_live_api: bool = True):
should conform with the other one

2024-10-19 23:44 UTC, echavemann commented on src/pysrc/adapters/kraken/spot/kraken_client.py
> +            res: Dict[str, Any] = response.json()
can we use str, object? best not to use any if possinle

2024-10-19 23:45 UTC, echavemann commented on src/pysrc/adapters/kraken/spot/kraken_client.py
> +        pairs: list[Asset],
assets

2024-10-19 23:46 UTC, echavemann commented on src/pysrc/adapters/kraken/spot/kraken_client.py
> +        pairs: list[Asset],
isnt this an optional param

2024-10-19 23:47 UTC, echavemann commented on src/pysrc/adapters/kraken/spot/kraken_client.py
> +        self, asset: Asset, interval: int = 1, since: Optional[int] = None
rename these besides asset to make more sense at a glance

2024-10-19 23:48 UTC, echavemann commented on src/pysrc/adapters/kraken/spot/kraken_client.py
> +    def get_order_book(self, asset: Asset, count: int = 100) -> SnapshotMessage:
can we sanitize the values of count

2024-10-19 23:48 UTC, echavemann commented on src/pysrc/adapters/kraken/spot/kraken_client.py
> +    def get_order_book(self, asset: Asset, count: int = 100) -> SnapshotMessage:
better param name too

2024-10-19 23:48 UTC, echavemann commented on src/pysrc/adapters/kraken/spot/kraken_client.py
> +        self, asset: Asset, since: Optional[int] = None, count: int = 1000
same as above

2024-10-19 23:49 UTC, echavemann commented on src/pysrc/test/integration/kraken/test_kraken_client.py
we should test system status for testnet and live, and the rest only for testnet

2024-10-19 23:52 UTC, echavemann commented on src/pysrc/util/conversions.py
> +T = TypeVar("T", bound=Enum)
i dont think you have to do this in 3.12 maybe... https://github.com/python/mypy/issues/15238

2024-10-19 23:52 UTC, echavemann commented on src/pysrc/util/conversions.py
you add these, you unit test these. better name of file too.

2024-10-19 23:53 UTC, echavemann commented on src/pysrc/util/conversions.py
also missing pr title and description, bad branch name

2024-10-20 00:01 UTC, aidanvillasenor commented on src/pysrc/adapters/kraken/spot/kraken_client.py
> +        self._kraken_to_asset = {"XXBTZUSD": Asset.BTC}
idk what u mean lol

2024-10-20 00:01 UTC, aidanvillasenor commented on src/pysrc/adapters/kraken/spot/kraken_client.py
> +    def __init__(self, use_live_api: bool = True):
in what way? Structure conforms with #30 . Are you talking about naming?

2024-10-20 00:01 UTC, aidanvillasenor commented on src/pysrc/adapters/kraken/spot/kraken_client.py
> +            res: Dict[str, Any] = response.json()
Nah it doesnt like it

2024-10-20 00:06 UTC, aidanvillasenor commented on src/pysrc/adapters/kraken/spot/kraken_client.py
> +        pairs: list[Asset],
yeah it is but if u dont put it it dumps a lotta stuff that you just don't care about. I made it required for now given that we don't have a ton of assets

2024-10-20 00:10 UTC, aidanvillasenor commented on src/pysrc/adapters/kraken/spot/kraken_client.py
> +    def get_order_book(self, asset: Asset, count: int = 100) -> SnapshotMessage:
was doing this before but I thought we decided to let the API handle this. Im cool w either but just wanna make sure before we pull the trigger on one

2024-10-20 00:13 UTC, aidanvillasenor commented on src/pysrc/test/integration/kraken/test_kraken_client.py
https://support.kraken.com/hc/en-us/articles/360000919926-Does-Kraken-offer-an-API-test-environment-

2024-10-20 01:06 UTC, echavemann commented on src/pysrc/adapters/kraken/spot/kraken_client.py
> +    def __init__(self, use_live_api: bool = True):
was about testnet, but dont we need to drop the param?

2024-10-20 01:06 UTC, echavemann commented on src/pysrc/adapters/kraken/spot/kraken_client.py
> +        self._kraken_to_asset = {"XXBTZUSD": Asset.BTC}
why XXBTZUSD

2024-10-20 01:06 UTC, echavemann commented on src/pysrc/adapters/kraken/spot/kraken_client.py
> +        pairs: list[Asset],
ok, then just rename it

2024-10-20 01:08 UTC, echavemann commented on src/pysrc/adapters/kraken/spot/kraken_client.py
> +    def get_order_book(self, asset: Asset, count: int = 100) -> SnapshotMessage:
im fine as long as we itest the out of bounds on this one then

2024-10-20 01:22 UTC, aidanvillasenor commented on src/pysrc/adapters/kraken/spot/kraken_client.py
> +        self._kraken_to_asset = {"XXBTZUSD": Asset.BTC}
thats what kraken calls it I got no fucking clue lol

2024-10-20 01:36 UTC, echavemann commented on src/pysrc/adapters/kraken/spot/kraken_client.py
> +        self._kraken_to_asset = {"XXBTZUSD": Asset.BTC}
XXXXZZZZ is the format

2024-10-20 01:36 UTC, echavemann commented on src/pysrc/adapters/kraken/spot/kraken_client.py
> +        self._kraken_to_asset = {"XXBTZUSD": Asset.BTC}
BTC used to be BT which checks out

2024-10-20 01:37 UTC, echavemann commented on src/pysrc/adapters/kraken/spot/kraken_client.py
> +        self._kraken_to_asset = {"XXBTZUSD": Asset.BTC}
we need the rest of the assets tho and probably best to pull that interaction into a function

2024-10-20 01:47 UTC, aidanvillasenor commented on src/pysrc/adapters/kraken/spot/kraken_client.py
> +        self._kraken_to_asset = {"XXBTZUSD": Asset.BTC}
doesn't look like we can formulaically do this in a foolproof way. I hardcoded it for now, will look for a sol later if needed.

2024-10-20 01:58 UTC, echavemann commented on src/pysrc/adapters/kraken/asset_mappings.py
maybe better to rename the fns kraken_feedcode_to_asset and vv

2024-10-20 02:49 UTC, echavemann approved these changes

2024-10-20 03:01 UTC, echavemann requested changes
test paths are wrong, need to make them match the paths in pysrc

2024-10-20 04:52 UTC, echavemann approved these changes
very nice

2024-10-20 04:54 UTC, merged