48 feature eval computation
northwesternfintech/desk-monorepo pull request #55
Opened 2024-11-03 19:36 UTC by kyeoul

### Description

### Testing

### Impact

### Other

2024-11-03 19:37 UTC, kyeoul commented
questions:
- Where should I put the script
- does the overall outline look correct

2024-11-11 23:40 UTC, echavemann commented on src/pysrc/util/feature_eval.py
> +        snapshots = {}
ur dependent on ryan for this

2024-11-11 23:40 UTC, echavemann commented on src/pysrc/util/feature_eval.py
> +        # What is key?
key is assets

2024-11-22 19:34 UTC, kyeoul commented on src/pysrc/util/feature_eval.py
> +        # What is key?
done

2024-11-22 19:34 UTC, kyeoul commented on src/pysrc/util/feature_eval.py
> +        snapshots = {}
yes

2024-11-22 20:43 UTC, echavemann commented on src/pysrc/test/unit/util/test_feature_eval.py
> +# Test feature evaluation
bad comment

2024-11-22 20:43 UTC, echavemann commented on src/pysrc/util/feature_eval.py
why r we using dateutil

2024-11-22 20:43 UTC, echavemann commented on src/pysrc/util/feature_eval.py
> +        pass
del

2024-11-22 20:43 UTC, echavemann commented on src/pysrc/util/feature_eval.py
> +    def __init__(self, features: list[str], asset: str, start: datetime, end: datetime):
asset enum

2024-11-22 20:43 UTC, echavemann commented on src/pysrc/util/feature_eval.py
> +        for date in rrule(DAILY, dtstart=start, until=end):
can we do all the path manip with `pathlib`

2024-11-22 20:44 UTC, echavemann commented on src/pysrc/util/feature_eval.py
> +            print("huh")
bro

2024-11-22 20:53 UTC, rewong03 requested changes

2024-11-22 20:53 UTC, rewong03 commented on src/pysrc/util/feature_eval.py
> +        self.features = features
prefix with underscore pls

2024-11-22 20:53 UTC, rewong03 commented on src/pysrc/util/feature_eval.py
> +        trades_resource_path: str,
i think we should pass `resource_path` as a class parameter, and then we can do `resouce_path`/trades/asset/date.bin here

2024-11-22 20:53 UTC, rewong03 commented on src/pysrc/util/feature_eval.py
> +        for date in rrule(DAILY, dtstart=start, until=end):
not anything wrong with using but was there a reason you used rrule instead of doing this manually

2024-11-22 20:53 UTC, rewong03 commented on src/pysrc/util/feature_eval.py
> +        for trade, snapshot in data:
uhhhh i think this is assuming that trades/snapshots start at the same tick and have an entry for every tick which i don't think is guaranteed

2024-11-22 20:53 UTC, rewong03 commented on src/pysrc/util/feature_eval.py
> +        for trade, snapshot in data:
@echavemann

2024-11-22 22:12 UTC, kyeoul commented on src/pysrc/util/feature_eval.py
> +        self.features = features
prefix the helpers? are you talking about calculate_features()
I thought it wasn't a helper, but would it be better to combine calculate_features and evaluate_features into one "calc_and_eval_features" method

2024-11-22 22:21 UTC, kyeoul commented on src/pysrc/test/unit/util/test_feature_eval.py
> +# Test feature evaluation
removed

2024-11-22 22:21 UTC, kyeoul commented on src/pysrc/util/feature_eval.py
im stupid, removed and iterating with regular datetime

2024-11-22 22:21 UTC, kyeoul commented on src/pysrc/util/feature_eval.py
> +        pass
done

2024-11-22 22:21 UTC, kyeoul commented on src/pysrc/util/feature_eval.py
> +    def __init__(self, features: list[str], asset: str, start: datetime, end: datetime):
done

2024-11-22 22:22 UTC, kyeoul commented on src/pysrc/util/feature_eval.py
> +        for date in rrule(DAILY, dtstart=start, until=end):
yes, done

2024-11-22 22:22 UTC, kyeoul commented on src/pysrc/util/feature_eval.py
> +            print("huh")
😭

2024-11-22 22:22 UTC, kyeoul commented on src/pysrc/util/feature_eval.py
> +        trades_resource_path: str,
done

2024-11-22 22:22 UTC, kyeoul commented on src/pysrc/util/feature_eval.py
> +        for date in rrule(DAILY, dtstart=start, until=end):
i was dumb

2024-11-22 22:27 UTC, rewong03 commented on src/pysrc/util/feature_eval.py
> +        self.features = features
mb i meant like self._features = features

2024-11-26 02:51 UTC, echavemann commented on src/pysrc/util/feature_eval.py
> +        for trade, snapshot in data:
yea that is not guaranteed

2024-11-26 02:51 UTC, echavemann commented on src/pysrc/util/feature_eval.py
> +        for trade, snapshot in data:
may need to mute to use jerrys pr
not sure

2024-12-01 22:18 UTC, echavemann commented on src/pysrc/test/feature_eval_helpers.py
I think this was alr added by chris in #66

2025-01-18 23:05 UTC, echavemann commented
did this mostly

2025-01-18 23:05 UTC, closed without merging